---
abstract: 'Test::Class + Moose'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Class-Moose
provides:
  Test::Class::Moose:
    file: lib/Test/Class/Moose.pm
    version: 0.03
  Test::Class::Moose::Config:
    file: lib/Test/Class/Moose/Config.pm
    version: 0.03
  Test::Class::Moose::Load:
    file: lib/Test/Class/Moose/Load.pm
    version: 0.03
  Test::Class::Moose::Reporting:
    file: lib/Test/Class/Moose/Reporting.pm
    version: 0.03
  Test::Class::Moose::Reporting::Class:
    file: lib/Test/Class/Moose/Reporting/Class.pm
    version: 0.03
  Test::Class::Moose::Reporting::Method:
    file: lib/Test/Class/Moose/Reporting/Method.pm
    version: 0.03
  Test::Class::Moose::Reporting::Time:
    file: lib/Test/Class/Moose/Reporting/Time.pm
    version: 0
  Test::Class::Moose::Role::Reporting:
    file: lib/Test/Class/Moose/Role/Reporting.pm
    version: 0
requires:
  Moose: 2.0402
  Test::Most: 0.31
  Try::Tiny: 0.11
  namespace::autoclean: 0.13
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Ovid/test-class-moose
version: 0.03
